schema: "classroom50/repo-config/v1"
classroom: "ds112"
assignment: "portfolio"
owner:
  username: "ghappel"
  id: 326200250
  accepted_at: "2026-09-12T22:17:21Z"
source:
  owner: "mac-ds112-f26"
  owner_id: 323651608
  repo: "portfolio-template"
  branch: "main"
